# Generated by Django 4.2 on 2025-08-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('abstract', models.TextField(blank=True)),
                ('author', models.TextField()),
                ('published', models.DateField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('available_copies', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
