# Generated by Django 4.2 on 2025-08-11 06:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('abstract', models.TextField()),
                ('author', models.TextField()),
                ('published', models.DateField()),
                ('cover', models.CharField(blank=True, max_length=100, null=True)),
                ('genre', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('available_copies', models.IntegerField()),
            ],
            options={
                'db_table': 'books_book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('email', models.CharField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('profile_image', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(max_length=10)),
                ('is_active', models.BooleanField()),
                ('is_staff', models.BooleanField()),
            ],
            options={
                'db_table': 'users_customuser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('fulfilled', models.BooleanField(default=False)),
                ('ready_for_pickup', models.BooleanField(default=False)),
                ('returned', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.customuser')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('cancelled', False), ('returned', False)), fields=('user', 'book_id'), name='unique_active_reservation'),
        ),
    ]
