# Generated by Django 4.2 on 2025-04-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('abstract', models.TextField(blank=True)),
                ('author', models.TextField()),
                ('published', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('checked_out', 'Checked Out'), ('lost', 'Lost')], default='available', max_length=20)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
