# Generated by Django 4.2 on 2025-07-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('not_available', 'not available'), ('in_queue', 'In Queue')], default='available', max_length=20),
        ),
    ]
