# Generated by Django 4.2 on 2025-04-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tatus',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('checked_out', 'Checked Out'), ('lost', 'Lost')], default='available', max_length=20),
        ),
    ]
