# Generated by Django 4.2 on 2025-07-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookline', '0002_alter_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available_copies',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
