# Generated by Django 4.2 on 2025-08-04 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookline', '0003_book_available_copies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
    ]
